<table>
    <thead>
    <tr>
        <th>nombres</th>
        <th>apellidos</th>
        <th>celular</th>
        <th>correo_personal</th>
        <th>origen_id</th>
        <th>referido_por</th>
        <th>otro_origen</th>
        <th>tipo_documento_id</th>
        <th>identificacion</th>
        <th>prefijo_id</th>        
        <th>fecha_nacimiento</th>
        <th>genero_id</th>
        <th>estado_civil_id</th>        
        <th>telefono</th>        
        <th>correo_institucional</th>
        <th>lugar_residencia</th>
        <th>direccion_residencia</th>
        <th>estrato</th>
        <th>observacion</th>        
        <th>maximo_nivel_formacion_id</th>
        <th>ocupacion_actual_id</th>
        <th>estilo_vida_id</th>
        <th>religion_id</th>
        <th>raza_id</th>
        <th>generacion_id</th>
        <th>personalidad_id</th>
        <th>beneficio_id</th>
        <th>frecuencia_uso_id</th>
        <th>estatus_usuario_id</th>
        <th>estatus_lealtad_id</th>
        <th>estado_disposicion_id</th>
        <th>actitud_servicio_id</th>
        <th>autoriza_comunicacion</th>
    </tr>
    </thead>
    <tbody>  
    </tbody>
</table>
