# docker image
image: chilio/laravel-dusk-ci:php-7.3

# Pick zero or more services to be used on all builds.
services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: crmUAM
  MYSQL_DATABASE: crm
  MYSQL_USER: crm
  MYSQL_PASSWORD: crmUAM

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - vendor
  - node_modules

before_script:  
  # Update Composer
  - composer self-update  
  
  # Install project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  
  - chmod -R 775 storage
  - chmod 775 bootstrap/cache
  - chown -R www-data ./

  # Copy over testing configuration.
  - cp .env.gitlab .env

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache
  - php artisan config:clear

  # Run database migrations.
  - php artisan migrate --seed
  
  # Other configurations
  - start-nginx-ci-project

test:
  script:
  # run tests
  - echo "Running PHPUnit Tests"
  - php artisan test --color
  
  - echo "Running Laravel Dusk"
  - php artisan dusk --colors --debug

  artifacts:
    paths:
      - ./storage/logs # for debugging
      # - ./tests/Browser/screenshots
      # - ./tests/Browser/console
    expire_in: 7 days
    when: always

deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=crmuam --api-key=$HEROKU_API_KEY
  only:
    - master